### ISSUE TITLE
Expand/ Collapse buttons for tree grid view

### ISSUE THREAD

**Issue by sachinbijadi** [ArasLabs/tree-grid-view-sample#6]
How do we add a the + and - buttons on the tree grid view to expand and collapse structure. If that is not possible can the tree grid view be made to generate directly in the expanded state instead of collapsed state? Because it is super annoying to have to hit and expand on the +'s for each line.

**Comment by sachinbijadi** [comment]
Also, how do you add links to the items in teh TGV, so when you click on them (or double click) they take you their form?

**Comment by sachinbijadi** [comment]
Anybody? @EliJDonahue?
This really seems like a mised opportunity to make the TGV really powerful to users

**Comment by EliJDonahue** [comment]
Hi sachinbijadi,

Regarding your first question - I believe tree grid views currently load in a collapsed view for performance reasons. However, you can quickly expand a tree using the "grow" button. It looks like a tree or a branch:

![image](https://user-images.githubusercontent.com/6794866/49026032-dfe5b200-f16a-11e8-98a7-507f86de4059.png)

Regarding your second question - It is possible to create clickable links in the tree grid view that open an Aras item in its form. You just need to use the "Item" Cell View Type and enter/point to the item's ItemType and a property containing its id.

![image](https://user-images.githubusercontent.com/6794866/49026284-76b26e80-f16b-11e8-92d0-23e4e0069036.png)

Hope this helps!

**Comment by sachinbijadi** [comment]
Thanks @EliJDonahue 
For the first tip, I am using TGVs on SP12, so the grow functionality is not available to me. Is there a workaround to create grow type button manually (as long as it is not too complicated)

For the second tip, works beautifully. Thanks!

**Comment by AngelaIp** [comment]
Hi,
I use Aras SP11 and also missed many functions that were available in the later SP versions. For TGV, many of the later funnctionality is often included in a basic way in lower service pack numbers. So there is a change that missing functions are already available, but not implemented yet. I was able to unlock a few of these in my SP11 version (e.g. the icon chooser). When you have SP15 running, you could also try to merge the missing code by yourself.  
Would Aras recommed you to do that? - No, definitely not! There are 1000 things that can go wrong! But I can confirm that on a small scale it´s possible to do.

**Comment by sachinbijadi** [comment]
@AngelaIp / @EliJDonahue : So how exactly do you recommend to make some sort of expand feature  in SP12's TGV?

**Comment by AngelaIp** [comment]
My described example should only show that it is theoretically possible to add this kind of additonial functionality by yourself. But I don´t think anybody can provide you a ready-to-use solution here. It´s not the standard way do add additional features.
I think for this use case an Aras update would be the easiest and most secure way to get the expand button!

**Comment by sachinbijadi** [comment]
is it somehow possible to add the code in the TGV method (say when creating TGV for TOC) for the + & - buttons and their actions like in the code of the Part MultiBOM relationship?

**Comment by AngelaIp** [comment]
Ah, I fully understand your situation! To hell with all the official recommendations, you want to have this feature NOW! 

And also I am the last person to stop your enthusiasm - this change must be made at the codetree level! You have to find the corresponding files (you can use your browser dev tools), understand how they works and try to get things running without destroying 5 other features on your way.  
This conflicts with your requirement **"(as long as it is not too complicated)."** :satisfied:

**Comment by sachinbijadi** [comment]
Damn! OK Never mind!
