### ISSUE TITLE
Help needed with Starting Parameters for Showing Tree Grid View in TOC

### ISSUE THREAD

**Issue by sachinbijadi** [ArasLabs/tree-grid-view-sample#7]
! Need help with code for starting parameters for Query to generate TGV in TOC Main Grid !

I have a simple Query Builder and TGV setup where I want ot look at all PRs that are in 'Pending' State (Where condition setup to filter out only pending PRs) and show any ECO's in which they have been addressed (I have modiefied the Express ECO itemtype to have relationship with PRs called "Addressed PRs"). In the QB i used the reference relationship of the PR back to a Expresse ECO it is linked to get the reverse linked Express ECOs (Refer Image).
![image](https://user-images.githubusercontent.com/42272230/49279671-66123900-f488-11e8-9518-7a06db120b06.png)

And associated TGV:
![image](https://user-images.githubusercontent.com/42272230/49279709-7cb89000-f488-11e8-92fb-5b67f46b0b71.png)

I am now trying to get this TGV to view in the TOC Main grid, to get a quick overview of all pending PRs and whether or not they have been addressed in ECOs to resolve them (this is quite business-critical for us). As suggested by @cgillis-aras  (Christopher) on the Community forum (https://community.aras.com/en/forums/topic/tree-view-in-main-grid/) I tried creating a form with html field with the code as suggested (tgv id modified). However it wouldn't render in the form preview because it had no starting parameter. So using the .Js method that can be generated from the TGV actions, as the reference, I tried to add the start condition parameters as shown next.
Method generated by TGV action:

```
var topWindow = aras.getMostTopWindowWithAras(window);
var tgvdIdParam;
var startConditionProviderParam;
var parametersProviderParam;
tgvdIdParam = 'tgvdId=E57AC319538944B1ADAC20910B0B0A9D';

/* Uncomment and customize the code below to customize startConditionProvider */
/*
topWindow.CustomStartConditionProvider = function(arg) {
	this.getCondition = function() {
		var idlist = ['ID1', 'ID2'];
		var managerId = arg; //"Innovator Admin" ID comes from the startConditionProviderParam args
		//id IN (idlist) AND managed_by_id = managerId
		return {
			'id': idlist,
			'managed_by_id': managerId
		};
	};
}

var managerIdentityId = 'DBA5D86402BF43D5976854B8B48FCDD1'; // "Innovator Admin" ID is for example
var managerIdentityIdUriEncoded = encodeURIComponent(managerIdentityId);
startConditionProviderParam = 'startConditionProvider=parent.CustomStartConditionProvider(' + managerIdentityIdUriEncoded + ')';
*/

/* Uncomment and modify the code below to customize parametersProvider */
/*
topWindow.CustomParametersProvider = function(arg) {
	var parameters = {
		'param1Name': 'param1Value',
		'param2Name': arg //'param2Value' comes from the parametersProviderParam args
	};
	this.getParameters = function() {
		return parameters;
	};
	this.setParameter = function(name, value) {
		//for the case if a parameter is updated by enduser in TGV UI.
		parameters[name] = value;
	};
}

var param2ValueUriEncoded = encodeURIComponent('param2Value');
parametersProviderParam = 'parametersProvider=parent.CustomParametersProvider(' + param2ValueUriEncoded + ')';
*/

// see more examples in Innovator\Client\Modules\aras.innovator.TreeGridView\Examples

var tgvUrl = aras.getBaseURL('/Modules/aras.innovator.TreeGridView/Views/MainPage.html?');
var allParams = [tgvdIdParam, startConditionProviderParam, parametersProviderParam];
for (var i = 0; i < allParams.length; i++) {
	if (allParams[i]) {
		tgvUrl += (i === 0 ? '' : '&') + allParams[i];
	}
}
var dialogParameters = {
	dialogWidth: 800,
	dialogHeight: 600,
	title: 'Tree Grid View Sample',
	content: tgvUrl
};
topWindow.ArasModules.MaximazableDialog.show('iframe', dialogParameters).promise.then(function() {
	delete topWindow.CustomStartConditionProvider;
	delete topWindow.CustomParametersProvider;
});
```

And here is the version I wrote, to insert into the html field in the form:
![image](https://user-images.githubusercontent.com/42272230/49280057-69f28b00-f489-11e8-9a9e-8b33467d5ba6.png)
```
	var topWindow = aras.getMostTopWindowWithAras(window);
	var tgvdIdParam;
	var startConditionProviderParam;
	tgvdIdParam = ‘tgvdId=E57AC319538944B1ADAC20910B0B0A9D’; 
  
	//Logic to specify custom Start Conditions
	topWindow.CustomStartConditionProvider = function(arg) {
		this.getCondition = function() {
			var idlist = ['1E0257392EDD48CB8DBF9708B22E2147'];
			//id of PR-100001
			return {
				'id': idlist,
			};
		};
	}
	startConditionProviderParam = 'startConditionProvider=parent.CustomStartConditionProvider(' + idlist + ')';
  
	//Logic to show Tree Grid Viewer in iframe. 
	var tgvUrl = aras.getBaseURL(‘/Modules/aras.innovator.TreeGridView/Views/MainPage.html?’);
	var allParams = [tgvdIdParam, startConditionProviderParam];
	for (var i = 0; i < allParams.length; i++) {
		if (allParams[i]) {
		tgvUrl += (i === 0 ? ” : ‘&’) + allParams[i];
		}
	}

	var iframe = document.createElement(‘iframe’);
	iframe.id = ‘tree_grid_viewer’;
	iframe.width = ‘100%’;
	iframe.height = ‘100%’;
	iframe.frameBorder = ‘0’;
	iframe.scrolling = ‘auto’;
	iframe.src = tgvUrl;
	document.body.insertBefore(iframe, document.body.childNodes[0]);
```
As you can see in the form snapshot, I am not getting any preview in the form, because I think the code for starting parameters is wrong. The Query Builder works just fine as can be seen below, so it is probably wrong coding for the start parameter i presume. Would greatly appreaciate help on how to write this code. I am not a coder, so I don't really understand how the syntax and arguments work. so some guidance would be really useful to get this working.
![image](https://user-images.githubusercontent.com/42272230/49280582-dc179f80-f48a-11e8-9bbd-a0c6a64d64b9.png)

**Comment by EliJDonahue** [comment]
Any thoughts on this one, @cgillis-aras?

**Comment by cgillis-aras** [comment]
The issue here is that when the TGV is opened via an **iframe** in the context of a Form or the Main Grid, the CustomStartConditionProvider is no longer being defined in a context that is accessible. A workaround to this issue is to change the very first line of the code from:
`var topWindow = aras.getMostTopWindowWithAras(window);`

to:
`var topWindow = window;`

The code that looks up this provider does by looking up **parent.CustomStartConditionProvider**. Because we've modified the code to display the TGV inside of a child **iframe** instead of a dialog, the context window of the Form itself becomes the parent. That's why this proposed change should resolve the issue.

**Comment by cgillis-aras** [comment]
@sachinbijadi Can you confirm if the proposed fix above resolved your issue?

**Comment by cgillis-aras** [comment]
@sachinbijadi I'm going to close this issue. If you notice a problem with the workaround in the future, please reply here, and I'll reopen the issue to help you get it working.
