### ISSUE TITLE
Adding a Parent relationship to show Parent part for a given part in query builder

### ISSUE THREAD

**Issue by sachinbijadi** [ArasLabs/tree-grid-view-sample#8]
Would greatly appreciate if somebody could somebody elaborate on how to set up a parent part relationship like shown in the following demo video from Aras (https://www.youtube.com/watch?v=c5ExpFtDGm4&feature=youtu.be), where in the Part Information view, we can see both Parent parts and Descendant parts. I realized that in that demo, there is a new relationship type created called Parent BOM

![image](https://user-images.githubusercontent.com/42272230/49388624-a55cb600-f724-11e8-9a56-c64fca46deb7.png)

![image](https://user-images.githubusercontent.com/42272230/49388663-bd343a00-f724-11e8-9297-c555f7e73d90.png)

![image](https://user-images.githubusercontent.com/42272230/49388710-dc32cc00-f724-11e8-9d63-d4ee47245ded.png)

![image](https://user-images.githubusercontent.com/42272230/49388901-52373300-f725-11e8-82d5-ae3177bd8243.png)

**Comment by AngelaIp** [comment]
I think they just renamed the label for BOM to Parent BOM. 

As far as I understand the sample, they unify two usecases.  Looking upward and downward. 
Part -> Add Related Item -> using Referencing Item -> Part BOM -> will display parent part
Part -> Add Related Item -> using Relationship -> BOM -> will display children. By using the resuse query element definition you will get a multilevel bom.

**Comment by sachinbijadi** [comment]
Thanks! That was quite the easy solution. I had used the right reference (Part BOM) but had used the BOM instance relationship instead of the source id property. Is working beautifully now.
